# Site settings
title: Zhijie Shen's Blog
email: zjshen14@gmail.com
description: >-
  A personal blog built with Jekyll and hosted on GitHub Pages.
  Share thoughts, tutorials, and experiences in technology and programming.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zjshen14.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima
permalink: /:year/:month/:day/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Social links
github_username: zjshen14

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md